export enum SCREEN_NAMES {
  ONBOARDING = 'ONBOARDING',
  AUTHORIZATION = 'AUTHORIZATION',
  INFO_GEO = 'INFO_GEO',
  ASK_GEO = 'ASK_GEO',
  FINISH_ONBOARDING = 'FINISH_ONBOARDING',
  MAIN = 'MAIN',
  MAP = 'MAP',
}
